name: lamna
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.0
  flutter_credit_card: ^4.0.1
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  indexed: ^0.0.8
  intl: ^0.19.0
  numberpicker: ^2.1.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logos/logo_mockup.png
    - assets/logos/logo.svg
    - assets/logos/logoSimple.svg
    - assets/logos/logo_google.png
    - assets/logos/logo_mac_os.png
    - assets/logos/logoLamnaApp.svg
    - assets/pictures/Location search_pana.png
    - assets/pictures/Madrid_pana.png
    - assets/pictures/Retail markdown_pana.png
    - assets/pictures/World Bicycle Day_pana.png
    - assets/pictures/directionsPana.png  
    - assets/pictures/rennes.png
    - assets/pictures/Rennes/rennes1.png
    - assets/pictures/Rennes/rennes2.png
    - assets/pictures/Rennes/rennes3.png
    - assets/pictures/Rennes/rennes_details_page.png
    - assets/pictures/saint_malo.png
    - assets/pictures/brest.png
    - assets/pictures/lorient.png
    - assets/json/cities.json
    - assets/json/busTravels.json
    - assets/json/covoitTravels.json
    - assets/json/trainTravels.json
    - assets/pictures/itinerary/itinerary1.png
    - assets/pictures/itinerary/itinerary2.png
    - assets/logos/darkIconTypo.svg
    - assets/itineraryCards/route1.png
    - assets/itineraryCards/route2.png
    - assets/itineraryCards/route3.png
    - assets/itineraryCards/route4.png
    - assets/itineraryCards/route5.png
    - assets/itineraryCards/route6.png
    - assets/icons/chevron-left-double.svg
    - assets/icons/chevron-right-double.svg
    - assets/icons/like.png
    - assets/icons/unlike.png
    - assets/avatar/avatar.jpg
    - assets/icons/clock-refresh.svg
    - assets/icons/info-circle.svg
    - assets/icons/right.svg
    - assets/icons/settings-01.svg
    - assets/icons/users-01.svg
    - assets/icons/trendDown.svg
    - assets/icons/busEmoji.png
    - assets/icons/trainEmoji.png
    - assets/icons/voitureEmoji.png
    - assets/mastercard/bgDark.png
    - assets/mastercard/bgLight.png
    - assets/mastercard/cardBg.png
    - assets/mastercard/mastercard.png
  fonts:
    - family: ClashDisplay
      fonts: 
        - asset: fonts/ClashDisplay-Variable.ttf
    - family: ClashDisplayBold
      fonts: 
        - asset: fonts/ClashDisplay-Bold.ttf
    - family: ClashDisplayLight
      fonts: 
        - asset: fonts/ClashDisplay-Light.ttf
    - family: ClashDisplayMedium
      fonts: 
        - asset: fonts/ClashDisplay-Medium.ttf
    - family: ClashDisplayRegular
      fonts: 
        - asset: fonts/ClashDisplay-Regular.ttf
    - family: ClashDisplaySemiBold
      fonts: 
        - asset: fonts/ClashDisplay-Semibold.ttf
    - family: InterBlack
      fonts: 
        - asset: fonts/Inter-Black.ttf
    - family: InterBold
      fonts: 
        - asset: fonts/Inter-Bold.ttf
    - family: InterExtraBold
      fonts: 
        - asset: fonts/Inter-ExtraBold.ttf
    - family: InterExtraLight
      fonts: 
        - asset: fonts/Inter-ExtraLight.ttf
    - family: InterLight
      fonts: 
        - asset: fonts/Inter-Light.ttf
    - family: InterMedium
      fonts: 
        - asset: fonts/Inter-Medium.ttf
    - family: InterRegular
      fonts: 
        - asset: fonts/Inter-Regular.ttf
    - family: InterSemiBold
      fonts: 
        - asset: fonts/Inter-SemiBold.ttf
    - family: InterThin
      fonts: 
        - asset: fonts/Inter-Thin.ttf
    
