name: lamna
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_card_swiper: ^6.0.0
  flutter_svg: ^2.0.9
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/logo_mockup.png
    - assets/logos/logo.svg
    - assets/logos/logoSimple.svg
    - assets/logos/logo_google.png
    - assets/logos/logo_mac_os.png
    - assets/pictures/Location search_pana.png
    - assets/pictures/Madrid_pana.png
    - assets/pictures/Retail markdown_pana.png
    - assets/pictures/World Bicycle Day_pana.png
    - assets/pictures/rennes.png
    - assets/pictures/Rennes/rennes1.png
    - assets/pictures/Rennes/rennes2.png
    - assets/pictures/Rennes/rennes3.png
    - assets/pictures/Rennes/rennes_details_page.png
    - assets/pictures/saint_malo.png
    - assets/pictures/brest.png
    - assets/pictures/lorient.png
    - assets/json/cities.json
    - assets/pictures/itinerary/itinerary1.png
    - assets/pictures/itinerary/itinerary2.png
    - assets/logos/darkIconTypo.svg
    - assets/itineraryCards/route1.png
    - assets/itineraryCards/route2.png
    - assets/itineraryCards/route3.png
    - assets/itineraryCards/route4.png
    - assets/itineraryCards/route5.png
    - assets/itineraryCards/route6.png
    - assets/icons/chevron-left-double.svg
    - assets/icons/chevron-right-double.svg
    - assets/icons/like.png
    - assets/icons/unlike.png
  fonts:
    - family: ClashDisplay
      fonts: 
        - asset: fonts/ClashDisplay-Variable.ttf
    - family: ClashDisplayBold
      fonts: 
        - asset: fonts/ClashDisplay-Bold.ttf
    - family: ClashDisplayLight
      fonts: 
        - asset: fonts/ClashDisplay-Light.ttf
    - family: ClashDisplayMedium
      fonts: 
        - asset: fonts/ClashDisplay-Medium.ttf
    - family: ClashDisplayRegular
      fonts: 
        - asset: fonts/ClashDisplay-Regular.ttf
    - family: ClashDisplaySemiBold
      fonts: 
        - asset: fonts/ClashDisplay-Semibold.ttf
